#!/bin/bash

day=$(date +'%d')
cuser="${SUDO_USER:-$USER}"
function theme_installed_directory {
    if [ -d /home/"$cuser"/.local/share/icons/"$1"/ ]; then
        dir=/home/"$cuser"/.local/share/icons/"$1"/
    elif [ -d /home/"$cuser"/.icons/"$1"/ ]; then
        dir=/home/"$cuser"/.icons/"$1"/
    elif [ -d /usr/share/icons/"$1"/ ]; then
         dir=/usr/share/icons/"$1"/
    else
        dir=false
    fi
    echo "$dir"
}

function apply_on_icon_theme {
    if [ -d "$1" ]; then 
        cd "$1""48/apps" || exit
        ln -sf calendar-blue-"$day".svg google-calendar.svg
        ln -sf calendar-purple-"$day".svg ms-calendar.svg
        ln -sf calendar-red-"$day".svg office-calendar.svg
        gtk-update-icon-cache --force "$1"
    fi
}


circle_dir=$(theme_installed_directory "Numix-Circle")
square_dir=$(theme_installed_directory "Numix-Square")
base_dir=$(theme_installed_directory "Numix")

apply_on_icon_theme "$circle_dir"
apply_on_icon_theme "$square_dir"

if [ -d "$base_dir" ]; then 
    cd $base_dir || exit
    places=$(find . -name "places" -type d ! -path "*/scalable/*")
    for place in $places
        do
            cd "$base_dir$place" || exit
            ln -sf calendar-"$day".svg calendar.svg
        done
    gtk-update-icon-cache --force $base_dir
fi
