#!/bin/bash

day=$(date +'%d')

cuser="${SUDO_USER:-$USER}"
circle=true
if [ -d /home/"$cuser"/.local/share/icons/Numix-Circle/ ]; then
    dir=/home/"$cuser"/.local/share/icons/Numix-Circle/
elif [ -d /home/"$cuser"/.icons/Numix-Circle/ ]; then
    dir=/home/"$cuser"/.icons/Numix-Circle/
elif [ -d /usr/share/icons/Numix-Circle/ ]; then
     dir=/usr/share/icons/Numix-Circle/
else
    circle=false
fi

base=true
if [ -d /home/"$cuser"/.local/share/icons/Numix/ ]; then
    dir2=/home/"$cuser"/.local/share/icons/Numix
elif [ -d /home/"$cuser"/.icons/Numix/ ]; then
    dir2=/home/"$cuser"/.icons/Numix/
elif [ -d /usr/share/icons/Numix/ ]; then
     dir2=/usr/share/icons/Numix/
else
    base=false
fi

if $circle; then 
    cd $dir"48x48/apps" || exit
    ln -sf calendar-blue-"$day".svg google-calendar.svg
    ln -sf calendar-purple-"$day".svg ms-calendar.svg
    ln -sf calendar-red-"$day".svg office-calendar.svg
    gtk-update-icon-cache --force $dir
fi

if $base; then 
    cd $dir2 || exit
    places=$(find . -name "places" -type d)
    for place in $places
        do
            cd "$dir2$place" || exit
            ln -sf calendar-"$day".svg calendar.svg
        done
    gtk-update-icon-cache --force $dir2
fi
